In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/openfootball/football.json/master/2020-21/en.1.json"

raw = pd.read_json(url)

raw

In [2]:
matches = raw["matches"]
matches

0      {'round': 'Matchday 1', 'date': '2020-09-12', ...
1      {'round': 'Matchday 1', 'date': '2020-09-12', ...
2      {'round': 'Matchday 1', 'date': '2020-09-12', ...
3      {'round': 'Matchday 1', 'date': '2020-09-12', ...
4      {'round': 'Matchday 1', 'date': '2020-09-13', ...
                             ...
375    {'round': 'Matchday 38', 'date': '2021-05-23',...
376    {'round': 'Matchday 38', 'date': '2021-05-23',...
377    {'round': 'Matchday 38', 'date': '2021-05-23',...
378    {'round': 'Matchday 38', 'date': '2021-05-23',...
379    {'round': 'Matchday 38', 'date': '2021-05-23',...
Name: matches, Length: 380, dtype: object

In [3]:
matches = pd.json_normalize(raw["matches"])
matches

,round,date,time,team1,team2,score.ht,score.ft
0,Matchday 1,2020-09-12,12:30,Fulham FC,Arsenal FC,"[0, 1]","[0, 3]"
1,Matchday 1,2020-09-12,15:00,Crystal Palace FC,Southampton FC,"[1, 0]","[1, 0]"
2,Matchday 1,2020-09-12,17:30,Liverpool FC,Leeds United FC,"[3, 2]","[4, 3]"
3,Matchday 1,2020-09-12,20:00,West Ham United FC,Newcastle United FC,"[0, 0]","[0, 2]"
4,Matchday 1,2020-09-13,14:00,West Bromwich Albion FC,Leicester City FC,"[0, 0]","[0, 3]"
...,...,...,...,...,...,...,...
375,Matchday 38,2021-05-23,16:00,Sheffield United FC,Burnley FC,"[1, 0]","[1, 0]"
376,Matchday 38,2021-05-23,16:00,Leicester City FC,Tottenham Hotspur FC,"[1, 1]","[2, 4]"
377,Matchday 38,2021-05-23,16:00,West Ham United FC,Southampton FC,"[2, 0]","[3, 0]"
378,Matchday 38,2021-05-23,16:00,Leeds United FC,West Bromwich Albion FC,"[2, 0]","[3, 1]"
379,Matchday 38,2021-05-23,16:00,Wolverhampton Wanderers FC,Manchester United FC,"[1, 2]","[1, 2]"

In [4]:
df= matches[["date","round","team1","team2","score.ft"]].copy()
df

,date,round,team1,team2,score.ft
0,2020-09-12,Matchday 1,Fulham FC,Arsenal FC,"[0, 3]"
1,2020-09-12,Matchday 1,Crystal Palace FC,Southampton FC,"[1, 0]"
2,2020-09-12,Matchday 1,Liverpool FC,Leeds United FC,"[4, 3]"
3,2020-09-12,Matchday 1,West Ham United FC,Newcastle United FC,"[0, 2]"
4,2020-09-13,Matchday 1,West Bromwich Albion FC,Leicester City FC,"[0, 3]"
...,...,...,...,...,...
375,2021-05-23,Matchday 38,Sheffield United FC,Burnley FC,"[1, 0]"
376,2021-05-23,Matchday 38,Leicester City FC,Tottenham Hotspur FC,"[2, 4]"
377,2021-05-23,Matchday 38,West Ham United FC,Southampton FC,"[3, 0]"
378,2021-05-23,Matchday 38,Leeds United FC,West Bromwich Albion FC,"[3, 1]"
379,2021-05-23,Matchday 38,Wolverhampton Wanderers FC,Manchester United FC,"[1, 2]"

In [5]:
df.columns=["match_date","round","home_team","away_team","final_score"]
df

,match_date,round,home_team,away_team,final_score
0,2020-09-12,Matchday 1,Fulham FC,Arsenal FC,"[0, 3]"
1,2020-09-12,Matchday 1,Crystal Palace FC,Southampton FC,"[1, 0]"
2,2020-09-12,Matchday 1,Liverpool FC,Leeds United FC,"[4, 3]"
3,2020-09-12,Matchday 1,West Ham United FC,Newcastle United FC,"[0, 2]"
4,2020-09-13,Matchday 1,West Bromwich Albion FC,Leicester City FC,"[0, 3]"
...,...,...,...,...,...
375,2021-05-23,Matchday 38,Sheffield United FC,Burnley FC,"[1, 0]"
376,2021-05-23,Matchday 38,Leicester City FC,Tottenham Hotspur FC,"[2, 4]"
377,2021-05-23,Matchday 38,West Ham United FC,Southampton FC,"[3, 0]"
378,2021-05-23,Matchday 38,Leeds United FC,West Bromwich Albion FC,"[3, 1]"
379,2021-05-23,Matchday 38,Wolverhampton Wanderers FC,Manchester United FC,"[1, 2]"

In [6]:
df["home_goals"] = df["final_score"].apply(lambda x: x[0] if isinstance(x, list) else None)
df["away_goals"] = df["final_score"].apply(lambda x: x[1] if isinstance(x, list) else None)

df.drop(columns=["final_score"], inplace=True)

df

,match_date,round,home_team,away_team,home_goals,away_goals
0,2020-09-12,Matchday 1,Fulham FC,Arsenal FC,0,3
1,2020-09-12,Matchday 1,Crystal Palace FC,Southampton FC,1,0
2,2020-09-12,Matchday 1,Liverpool FC,Leeds United FC,4,3
3,2020-09-12,Matchday 1,West Ham United FC,Newcastle United FC,0,2
4,2020-09-13,Matchday 1,West Bromwich Albion FC,Leicester City FC,0,3
...,...,...,...,...,...,...
375,2021-05-23,Matchday 38,Sheffield United FC,Burnley FC,1,0
376,2021-05-23,Matchday 38,Leicester City FC,Tottenham Hotspur FC,2,4
377,2021-05-23,Matchday 38,West Ham United FC,Southampton FC,3,0
378,2021-05-23,Matchday 38,Leeds United FC,West Bromwich Albion FC,3,1
379,2021-05-23,Matchday 38,Wolverhampton Wanderers FC,Manchester United FC,1,2

In [7]:
df["match_date"] = pd.to_datetime(df["match_date"]).dt.date
df = df.dropna()
df = df.drop_duplicates()

df

,match_date,round,home_team,away_team,home_goals,away_goals
0,2020-09-12,Matchday 1,Fulham FC,Arsenal FC,0,3
1,2020-09-12,Matchday 1,Crystal Palace FC,Southampton FC,1,0
2,2020-09-12,Matchday 1,Liverpool FC,Leeds United FC,4,3
3,2020-09-12,Matchday 1,West Ham United FC,Newcastle United FC,0,2
4,2020-09-13,Matchday 1,West Bromwich Albion FC,Leicester City FC,0,3
...,...,...,...,...,...,...
375,2021-05-23,Matchday 38,Sheffield United FC,Burnley FC,1,0
376,2021-05-23,Matchday 38,Leicester City FC,Tottenham Hotspur FC,2,4
377,2021-05-23,Matchday 38,West Ham United FC,Southampton FC,3,0
378,2021-05-23,Matchday 38,Leeds United FC,West Bromwich Albion FC,3,1
379,2021-05-23,Matchday 38,Wolverhampton Wanderers FC,Manchester United FC,1,2

In [8]:
df["total_goals"] = df["home_goals"] + df["away_goals"]

In [10]:
print(df.head())
print(df.info())

   match_date       round                home_team            away_team  \
0  2020-09-12  Matchday 1                Fulham FC           Arsenal FC
1  2020-09-12  Matchday 1        Crystal Palace FC       Southampton FC
2  2020-09-12  Matchday 1             Liverpool FC      Leeds United FC
3  2020-09-12  Matchday 1       West Ham United FC  Newcastle United FC
4  2020-09-13  Matchday 1  West Bromwich Albion FC    Leicester City FC

   home_goals  away_goals  total_goals
0           0           3            3
1           1           0            1
2           4           3            7
3           0           2            2
4           0           3            3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_date   380 non-null    object
 1   round        380 non-null    object
 2   home_team    380 non-null    object
 3   away_team    380 non-null    object
 4   home_goals   380 non-null    int64
 5   away_goals   380 non-null    int64
 6   total_goals  380 non-null    int64
dtypes: int64(3), object(4)
memory usage: 20.9+ KB
None

In [25]:
import snowflake.connector

conn = snowflake.connector.connect(
    user="SIDDHARTH",
    password="FrankLampard@08",
    account="KLDLPCI-RUB00312",
    warehouse="COMPUTE_WH",
    database="Assignment",
    schema="PUBLIC"
)

cursor = conn.cursor()

for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO football_matches
        (match_date, round, home_team, away_team,
         home_goals, away_goals, total_goals)
        VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()

In [ ]:
# create database Assignment;
# CREATE OR REPLACE TABLE football_matches (
#     match_date DATE,
#     round STRING,
#     home_team STRING,
#     away_team STRING,
#     home_goals INTEGER,
#     away_goals INTEGER,
#     total_goals INTEGER
# );
# select * from football_matches

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

#for classification

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier